window.ORAKLO_DEMO_USER = {
  username: "@Usuario",
  karma: 1000,
  prestigio: 0,
  rango: "Observador"
};

window.ORAKLO_MARKETS = [
  {
    id: "gta-vi-retraso",
    pregunta: "¿GTA VI se retrasará oficialmente a 2027?",
    categoria: "Lanzamientos",
    estado: "Abierto",
    porcentajeSi: 42,
    porcentajeNo: 58,
    dificultad: "Normal",
    karmaTotal: 1240,
    participantes: 328,
    comentarios: 86,
    cierre: "Cierra en 3 días",
    cierreFecha: "2026-07-12",
    descripcion: "Mercado sobre si Rockstar Games comunicará oficialmente que GTA VI pasa a lanzarse en 2027.",
    fuenteResolucion: "Comunicado oficial de Rockstar Games o Take-Two Interactive.",
    criterioSi: "Gana el Sí si una fuente oficial confirma que GTA VI se retrasa a cualquier fecha de 2027.",
    criterioNo: "Gana el No si no existe anuncio oficial de retraso a 2027 antes del cierre o si se mantiene una fecha de 2026.",
    casoDudoso: "Rumores, filtraciones o cambios en tiendas sin confirmación oficial no bastan para resolver el mercado.",
    destacado: true,
    popularidad: 98,
    fechaCreacion: "2026-07-01"
  },
  {
    id: "silksong-90-metacritic",
    pregunta: "¿Hollow Knight: Silksong tendrá 90 o más en Metacritic?",
    categoria: "Reviews/Premios",
    estado: "Abierto",
    porcentajeSi: 31,
    porcentajeNo: 69,
    dificultad: "Difícil",
    karmaTotal: 850,
    participantes: 124,
    comentarios: 32,
    cierre: "Cierra el 20/09/2026",
    cierreFecha: "2026-09-20",
    descripcion: "Predicción sobre la nota media de Hollow Knight: Silksong cuando haya suficientes reviews publicadas.",
    fuenteResolucion: "Página de Metacritic del juego en la plataforma principal indicada por consenso de reviews.",
    criterioSi: "Gana el Sí si la media visible en Metacritic es 90 o superior en el momento de resolución.",
    criterioNo: "Gana el No si la media visible en Metacritic es inferior a 90 en el momento de resolución.",
    casoDudoso: "Si hay varias plataformas con notas muy distintas, se usará la versión con más reviews registradas.",
    destacado: false,
    popularidad: 76,
    fechaCreacion: "2026-06-21"
  },
  {
    id: "nuevo-mario-3d-direct",
    pregunta: "¿Nintendo anunciará un nuevo Mario 3D en el próximo Direct?",
    categoria: "Eventos",
    estado: "Abierto",
    porcentajeSi: 54,
    porcentajeNo: 46,
    dificultad: "Normal",
    karmaTotal: 1720,
    participantes: 402,
    comentarios: 119,
    cierre: "Cierra en 6 días",
    cierreFecha: "2026-07-15",
    descripcion: "Mercado sobre si el próximo Nintendo Direct incluirá el anuncio de un nuevo Mario 3D principal.",
    fuenteResolucion: "Emisión oficial del Nintendo Direct y canales oficiales de Nintendo.",
    criterioSi: "Gana el Sí si Nintendo presenta un nuevo juego principal de Mario en 3D durante el Direct.",
    criterioNo: "Gana el No si no se anuncia un nuevo Mario 3D principal durante el Direct.",
    casoDudoso: "Remasters, DLC, spin-offs o cameos no cuentan salvo que Nintendo lo presente como nuevo Mario 3D principal.",
    destacado: false,
    popularidad: 94,
    fechaCreacion: "2026-07-06"
  },
  {
    id: "ibai-3m-espectadores",
    pregunta: "¿Ibai superará 3 millones de espectadores simultáneos antes del 31/12/2026?",
    categoria: "Streamers",
    estado: "Abierto",
    porcentajeSi: 24,
    porcentajeNo: 76,
    dificultad: "Muy difícil",
    karmaTotal: 960,
    participantes: 210,
    comentarios: 58,
    cierre: "Cierra el 31/12/2026",
    cierreFecha: "2026-12-31",
    descripcion: "Predicción sobre si un directo de Ibai alcanzará más de 3 millones de espectadores simultáneos.",
    fuenteResolucion: "Datos públicos de Twitch/YouTube y reportes de analítica ampliamente citados.",
    criterioSi: "Gana el Sí si un directo de Ibai supera oficialmente los 3.000.000 espectadores simultáneos antes de fin de 2026.",
    criterioNo: "Gana el No si no se supera esa cifra antes del 31/12/2026.",
    casoDudoso: "Si distintas fuentes discrepan, se priorizarán datos de plataforma o fuentes analíticas reconocidas.",
    destacado: false,
    popularidad: 82,
    fechaCreacion: "2026-07-03"
  },
  {
    id: "youtuber-gaming-10m",
    pregunta: "¿Un YouTuber gaming superará 10 millones de suscriptores antes de final de año?",
    categoria: "YouTubers",
    estado: "Abierto",
    porcentajeSi: 47,
    porcentajeNo: 53,
    dificultad: "Difícil",
    karmaTotal: 640,
    participantes: 98,
    comentarios: 21,
    cierre: "Cierra el 31/12/2026",
    cierreFecha: "2026-12-31",
    descripcion: "Mercado sobre crecimiento de canales gaming y si alguno superará la barrera de 10 millones de suscriptores.",
    fuenteResolucion: "Página pública del canal en YouTube y Social Blade como referencia secundaria.",
    criterioSi: "Gana el Sí si un canal gaming que aún no tenía 10 millones supera esa cifra antes de fin de año.",
    criterioNo: "Gana el No si ningún canal gaming nuevo supera los 10 millones antes del cierre.",
    casoDudoso: "Canales mixtos solo cuentan si su contenido principal reciente es gaming.",
    destacado: false,
    popularidad: 62,
    fechaCreacion: "2026-06-30"
  },
  {
    id: "xbox-adquisicion-estudio",
    pregunta: "¿Xbox anunciará una nueva adquisición de estudio este año?",
    categoria: "Industria",
    estado: "Abierto",
    porcentajeSi: 18,
    porcentajeNo: 82,
    dificultad: "Épica",
    karmaTotal: 1320,
    participantes: 286,
    comentarios: 74,
    cierre: "Cierra el 15/12/2026",
    cierreFecha: "2026-12-15",
    descripcion: "Predicción sobre movimientos corporativos de Xbox y la compra de un estudio de desarrollo.",
    fuenteResolucion: "Comunicados oficiales de Microsoft, Xbox o la empresa adquirida.",
    criterioSi: "Gana el Sí si Xbox/Microsoft anuncia oficialmente la adquisición de un estudio de videojuegos.",
    criterioNo: "Gana el No si no se anuncia una adquisición oficial antes del cierre.",
    casoDudoso: "Inversiones minoritarias, acuerdos de publishing o rumores de compra no cuentan como adquisición.",
    destacado: false,
    popularidad: 88,
    fechaCreacion: "2026-07-04"
  },
  {
    id: "indie-nominado-goty",
    pregunta: "¿Un juego indie será nominado a GOTY?",
    categoria: "Reviews/Premios",
    estado: "Abierto",
    porcentajeSi: 63,
    porcentajeNo: 37,
    dificultad: "Normal",
    karmaTotal: 1110,
    participantes: 250,
    comentarios: 67,
    cierre: "Cierra el 01/11/2026",
    cierreFecha: "2026-11-01",
    descripcion: "Mercado sobre si un juego independiente entrará en la categoría principal de Game of the Year.",
    fuenteResolucion: "Lista oficial de nominados de The Game Awards u organización indicada.",
    criterioSi: "Gana el Sí si al menos un juego indie aparece nominado en la categoría GOTY principal.",
    criterioNo: "Gana el No si ningún juego indie aparece nominado en la categoría GOTY principal.",
    casoDudoso: "La clasificación como indie se basará en editor, financiación y consenso de prensa especializada.",
    destacado: false,
    popularidad: 79,
    fechaCreacion: "2026-06-26"
  },
  {
    id: "state-of-play-junio-2026-wolverine",
    pregunta: "¿Apareció Marvel’s Wolverine en el State of Play del 2 de junio de 2026?",
    categoria: "Eventos",
    estado: "Resuelto",
    porcentajeSi: 50,
    porcentajeNo: 50,
    dificultad: "Fácil",
    karmaTotal: 0,
    participantes: 0,
    comentarios: 0,
    cierre: "Resuelto",
    cierreFecha: "2026-06-02T23:59:00Z",
    resultadoResolucion: "Sí",
    notaResolucion: "Marvel's Wolverine apareció como el anuncio principal del State of Play del 2 de junio de 2026. El evento incluyó gameplay, detalles de la historia y la confirmación de su fecha de lanzamiento.",
    fechaResolucion: "2026-07-14T19:33:40.360Z",
    fuentesResolucion: [
      {
        title: "State of Play June 2026: todos los anuncios y tráileres",
        url: "https://blog.playstation.com/2026/06/02/state-of-play-june-2026-all-announcements-trailers/",
        citedText: "El resumen oficial incluye Marvel’s Wolverine entre los contenidos destacados del evento."
      },
      {
        title: "Marvel’s Wolverine: nuevo gameplay y detalles de la historia",
        url: "https://blog.playstation.com/2026/06/02/marvels-wolverine-new-gameplay-story-details-from-state-of-play/",
        citedText: "PlayStation e Insomniac detallan el gameplay presentado durante el State of Play."
      }
    ],
    modeloResolucionIa: "gemini-3-flash-preview",
    fechaAnalisisIa: "2026-07-14T19:19:47.703Z",
    descripcion: "Mercado de prueba sobre la aparición de Marvel’s Wolverine en la emisión concreta de State of Play celebrada el 2 de junio de 2026.",
    fuenteResolucion: "Resumen oficial del State of Play de junio de 2026 y artículo oficial de Marvel’s Wolverine publicados en PlayStation Blog.",
    criterioSi: "Gana el Sí si la emisión o su resumen oficial incluyen un segmento, tráiler, gameplay o anuncio de Marvel’s Wolverine.",
    criterioNo: "Gana el No si Marvel’s Wolverine no aparece en la emisión ni en el listado oficial de anuncios del evento.",
    casoDudoso: "No cuentan noticias anteriores o posteriores que no formen parte de esa emisión concreta.",
    destacado: false,
    popularidad: 0,
    fechaCreacion: "2026-05-15"
  },
  {
    id: "state-of-play-este-mes",
    pregunta: "¿PlayStation anunciará un nuevo State of Play este mes?",
    categoria: "Eventos",
    estado: "Abierto",
    porcentajeSi: 69,
    porcentajeNo: 31,
    dificultad: "Fácil",
    karmaTotal: 720,
    participantes: 176,
    comentarios: 44,
    cierre: "Cierra el 28/07/2026",
    cierreFecha: "2026-07-28",
    descripcion: "Predicción sobre si PlayStation anunciará oficialmente una nueva emisión State of Play durante el mes actual.",
    fuenteResolucion: "PlayStation Blog, redes oficiales de PlayStation o canal oficial de YouTube.",
    criterioSi: "Gana el Sí si PlayStation anuncia oficialmente un State of Play antes de terminar el mes.",
    criterioNo: "Gana el No si no existe anuncio oficial durante el mes.",
    casoDudoso: "Eventos de terceros con presencia de PlayStation no cuentan como State of Play.",
    destacado: false,
    popularidad: 71,
    fechaCreacion: "2026-07-08"
  },
  {
    id: "kojima-trailer-5m",
    pregunta: "¿El próximo tráiler de Kojima Productions superará 5 millones de visualizaciones en 48 horas?",
    categoria: "Industria",
    estado: "Cerrado",
    porcentajeSi: 36,
    porcentajeNo: 64,
    dificultad: "Difícil",
    karmaTotal: 480,
    participantes: 73,
    comentarios: 18,
    cierre: "Pendiente de resolución",
    cierreFecha: "2026-07-10",
    descripcion: "Mercado sobre el rendimiento del próximo tráiler oficial de Kojima Productions en sus primeras 48 horas.",
    fuenteResolucion: "Canal oficial donde se publique el tráiler y contador público de visualizaciones.",
    criterioSi: "Gana el Sí si el tráiler supera 5 millones de visualizaciones dentro de las primeras 48 horas.",
    criterioNo: "Gana el No si no supera 5 millones de visualizaciones en ese periodo.",
    casoDudoso: "Reuploads no oficiales no cuentan. Si hay varios canales oficiales, se sumará solo si la campaña lo publica así.",
    destacado: false,
    popularidad: 48,
    fechaCreacion: "2026-06-18"
  },
  {
    id: "showcase-verano-first-party",
    pregunta: "¿El último showcase de verano tendría más de tres anuncios first party?",
    categoria: "Eventos",
    estado: "Resuelto",
    porcentajeSi: 57,
    porcentajeNo: 43,
    dificultad: "Normal",
    karmaTotal: 910,
    participantes: 201,
    comentarios: 53,
    cierre: "Resuelto",
    cierreFecha: "2026-06-15",
    resultadoResolucion: "Sí",
    notaResolucion: "El listado oficial confirmó más de tres anuncios first party.",
    fechaResolucion: "2026-06-16T10:00:00+02:00",
    descripcion: "Mercado de prueba resuelto sobre la cantidad de anuncios first party en un showcase de verano.",
    fuenteResolucion: "Listado oficial de anuncios del evento y resumen publicado por la compañía organizadora.",
    criterioSi: "Gana el Sí si hubo más de tres anuncios first party durante el showcase.",
    criterioNo: "Gana el No si hubo tres o menos anuncios first party.",
    casoDudoso: "Expansiones o actualizaciones solo cuentan si la compañía las presentó como anuncios first party relevantes.",
    destacado: false,
    popularidad: 66,
    fechaCreacion: "2026-05-22"
  }
];
